In [1]:
import numpy as np

In [3]:
#create rank 1 dim array
arr = np.array([1,2,3])
print("Rank 1 array")
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr[0],arr[1], arr[2])
arr[2] = 4
print(arr)

#create rank 2 array
arr2 = np.array([[1,2,3],[4,5,6]])
print("\nRank 2 array")
print(arr2.shape)
print(arr2[0,0], arr2[0,1],arr2[1,0])
print(arr2[-1])



Rank 1 array
<class 'numpy.ndarray'>
int32
(3,)
1 2 3
[1 2 4]

Rank 2 array
(2, 3)
1 2 4
[4 5 6]


In [4]:
# array indexing

arr = np.arange(10)
print(arr[0:8:2])

#create rank2 with shape (3,4) array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[:2,:2])

#integer indexing
arr = np.array([[1,2],[3,4],[5,6]])
print(arr[[0,1,2],[0,1,1]])

[0 2 4 6]
[[1 2]
 [5 6]]
[1 4 6]
